plugins {
    alias(libs.plugins.multiplatform).apply(false)
    alias(libs.plugins.compose.compiler).apply(false)
    alias(libs.plugins.compose).apply(false)
    alias(libs.plugins.android.application).apply(false)
    alias(libs.plugins.android.kotlin.multiplatform.library).apply(false)
    alias(libs.plugins.hotReload).apply(false)
    alias(libs.plugins.kotlinx.serialization).apply(false)
    alias(libs.plugins.buildConfig).apply(false)
    alias(libs.plugins.maven.publish).apply(false)
    alias(libs.plugins.sqlDelight).apply(false)
    alias(libs.plugins.metro).apply(false)
    alias(libs.plugins.caupain)
    alias(libs.plugins.linux.deps).apply(false)
}
