// DO NOT EDIT.
// This file is auto-generated by the catalog generator.
// To regenerate: ./gradlew :cataloggen:generatePrecomputedCatalog
// Manual changes will be lost.
@file:Suppress("ktlint")

package io.github.kdroidfilter.seforimapp.catalog

import kotlin.Long
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

public data class BookRef(
  public val id: Long,
  public val title: String,
)

public data class TocQuickLink(
  public val label: String,
  public val tocEntryId: Long,
  public val firstLineId: Long?,
)

public sealed interface DropdownSpec

public data class CategoryDropdownSpec(
  public val categoryId: Long,
) : DropdownSpec

public data class MultiCategoryDropdownSpec(
  public val labelCategoryId: Long,
  public val bookCategoryIds: List<Long>,
) : DropdownSpec

public data class TocQuickLinksSpec(
  public val bookId: Long,
  public val links: List<TocQuickLink>,
) : DropdownSpec

public object CatalogPresets {
  public object Ids {
    public object Categories {
      /**
       * תנ״ך
       */
      public const val TANAKH: Long = 1L

      /**
       * תורה
       */
      public const val TORAH: Long = 2L

      /**
       * נביאים
       */
      public const val NEVIIM: Long = 3L

      /**
       * כתובים
       */
      public const val KETUVIM: Long = 4L

      /**
       * משנה
       */
      public const val MISHNA: Long = 5L

      /**
       * סדר זרעים
       */
      public const val MISHNA_ZERAIM: Long = 6L

      /**
       * סדר מועד
       */
      public const val MISHNA_MOED: Long = 7L

      /**
       * סדר נשים
       */
      public const val MISHNA_NASHIM: Long = 8L

      /**
       * סדר נזיקין
       */
      public const val MISHNA_NEZIKIN: Long = 9L

      /**
       * סדר קדשים
       */
      public const val MISHNA_KODASHIM: Long = 10L

      /**
       * סדר טהרות
       */
      public const val MISHNA_TAHAROT: Long = 11L

      /**
       * בבלי
       */
      public const val BAVLI: Long = 13L

      /**
       * סדר זרעים
       */
      public const val BAVLI_ZERAIM: Long = 14L

      /**
       * סדר מועד
       */
      public const val BAVLI_MOED: Long = 15L

      /**
       * סדר נשים
       */
      public const val BAVLI_NASHIM: Long = 16L

      /**
       * סדר נזיקין
       */
      public const val BAVLI_NEZIKIN: Long = 17L

      /**
       * סדר קדשים
       */
      public const val BAVLI_KODASHIM: Long = 18L

      /**
       * סדר טהרות
       */
      public const val BAVLI_TAHAROT: Long = 19L

      /**
       * ירושלמי
       */
      public const val YERUSHALMI: Long = 20L

      /**
       * סדר זרעים
       */
      public const val YERUSHALMI_ZERAIM: Long = 21L

      /**
       * סדר מועד
       */
      public const val YERUSHALMI_MOED: Long = 22L

      /**
       * סדר נשים
       */
      public const val YERUSHALMI_NASHIM: Long = 23L

      /**
       * סדר נזיקין
       */
      public const val YERUSHALMI_NEZIKIN: Long = 24L

      /**
       * סדר טהרות
       */
      public const val YERUSHALMI_TAHAROT: Long = 25L

      /**
       * משנה תורה
       */
      public const val MISHNE_TORAH: Long = 45L

      /**
       * טור
       */
      public const val TUR: Long = 61L

      /**
       * שולחן ערוך
       */
      public const val SHULCHAN_ARUCH: Long = 62L
    }

    public object Books {
      /**
       * טור
       */
      public const val TUR: Long = 380L
    }

    public object TocTexts {
      /**
       * אורח חיים
       */
      public const val ORACH_CHAIM: Long = 3_878L

      /**
       * יורה דעה
       */
      public const val YOREH_DEAH: Long = 4_521L

      /**
       * אבן העזר
       */
      public const val EVEN_HAEZER: Long = 4_522L

      /**
       * חושן משפט
       */
      public const val CHOSHEN_MISHPAT: Long = 4_523L
    }
  }

  public object Dropdowns {
    public val HOME: List<DropdownSpec> = listOf(
          MultiCategoryDropdownSpec(1L, listOf(2L, 3L, 4L)),
          MultiCategoryDropdownSpec(5L, listOf(6L, 7L, 8L, 9L, 10L, 11L)),
          MultiCategoryDropdownSpec(13L, listOf(14L, 15L, 16L, 17L, 18L, 19L)),
          MultiCategoryDropdownSpec(20L, listOf(21L, 22L, 23L, 24L, 25L)),
          CategoryDropdownSpec(62L),
          TocQuickLinksSpec(380L, listOf(TocQuickLink("אורח חיים", 30_149L, 252_607), TocQuickLink("יורה דעה", 30_848L, 254_014), TocQuickLink("אבן העזר", 31_253L, 254_828), TocQuickLink("חושן משפט", 31_433L, 255_198))),
        )

    public val TANAKH: DropdownSpec = MultiCategoryDropdownSpec(1L, listOf(2L, 3L, 4L))

    public val TORAH: DropdownSpec = CategoryDropdownSpec(2L)

    public val NEVIIM: DropdownSpec = CategoryDropdownSpec(3L)

    public val KETUVIM: DropdownSpec = CategoryDropdownSpec(4L)

    public val MISHNA: DropdownSpec =
        MultiCategoryDropdownSpec(5L, listOf(6L, 7L, 8L, 9L, 10L, 11L))

    public val BAVLI: DropdownSpec =
        MultiCategoryDropdownSpec(13L, listOf(14L, 15L, 16L, 17L, 18L, 19L))

    public val YERUSHALMI: DropdownSpec =
        MultiCategoryDropdownSpec(20L, listOf(21L, 22L, 23L, 24L, 25L))

    public val SHULCHAN_ARUCH: DropdownSpec = CategoryDropdownSpec(62L)

    public val MISHNE_TORAH: DropdownSpec =
        MultiCategoryDropdownSpec(45L, listOf(46L, 47L, 48L, 49L, 50L, 51L, 52L, 53L, 54L, 55L, 59L, 56L, 57L, 58L, 60L))

    public val TUR_QUICK_LINKS: DropdownSpec =
        TocQuickLinksSpec(380L, listOf(TocQuickLink("אורח חיים", 30_149L, 252_607), TocQuickLink("יורה דעה", 30_848L, 254_014), TocQuickLink("אבן העזר", 31_253L, 254_828), TocQuickLink("חושן משפט", 31_433L, 255_198)))
  }
}
